[pytest]
filterwarnings =
    ignore::DeprecationWarning:botocore.* # botocore had a warning, and we have no control over their code:
    ignore::pytest.PytestRemovedIn9Warning # pluggy uses a feature removed in v9, we do not control their code