[pytest]
# the following packages had a warnings, and we have no control over their code:
# - botocore
# - pluggy
filterwarnings =
    ignore::DeprecationWarning:botocore.*
    ignore::pytest.PytestRemovedIn9Warning